name: A. Job Dependencies
on: push

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Building application...
        run: echo "Building application..."
      - name: Simulating build process
        run: sleep 5 

  test:
    name: Test Job
    runs-on: ubuntu-latest
    needs: build #waits for build to complete
    steps:
      - name: Running tests...
        run: echo "Running tests..."
      - name: Simulating test process
        run: echo "Tests complete."

  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    needs: test #waits for test to complete
    steps:
      - name: Deploying application...
        run: echo "Deploying application..."
      - name: Simulating deployment
        run: echo "Deployment complete."
